server:
  port: 8080

spring:
  application:
    name: akay
  datasource:
    url: jdbc:postgresql://localhost:5432/incdb
    username:
    password:
    jpa:
      hibernate:
        ddl-auto: create
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          format_sql: true
      show-sql: true